version: "3.5"

services:

  postgres:
    image: postgres
    restart: always
    container_name: movie_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"